//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6524.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN_variable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN_variable() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_6524.Resources.EN_variable", typeof(EN_variable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The language setting is complete and takes effect after restarting the program 的本地化字符串。
        /// </summary>
        internal static string changeLanguageinfo {
            get {
                return ResourceManager.GetString("changeLanguageinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC is connecting 的本地化字符串。
        /// </summary>
        internal static string PLC连接中 {
            get {
                return ResourceManager.GetString("PLC连接中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC connection failed 的本地化字符串。
        /// </summary>
        internal static string PLC连接失败 {
            get {
                return ResourceManager.GetString("PLC连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC connection completed 的本地化字符串。
        /// </summary>
        internal static string PLC连接完成 {
            get {
                return ResourceManager.GetString("PLC连接完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing 的本地化字符串。
        /// </summary>
        internal static string 初始化 {
            get {
                return ResourceManager.GetString("初始化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete images regularly 的本地化字符串。
        /// </summary>
        internal static string 定期删除图片中 {
            get {
                return ResourceManager.GetString("定期删除图片中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Failed to write PLC signals 的本地化字符串。
        /// </summary>
        internal static string 工位1写入PLC信号失败 {
            get {
                return ResourceManager.GetString("工位1写入PLC信号失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Send results 的本地化字符串。
        /// </summary>
        internal static string 工位1发送结果中 {
            get {
                return ResourceManager.GetString("工位1发送结果中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Sending results completed 的本地化字符串。
        /// </summary>
        internal static string 工位1发送结果完成 {
            get {
                return ResourceManager.GetString("工位1发送结果完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Image processing 的本地化字符串。
        /// </summary>
        internal static string 工位1图像处理中 {
            get {
                return ResourceManager.GetString("工位1图像处理中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1  Image processing completed 的本地化字符串。
        /// </summary>
        internal static string 工位1图像处理完成 {
            get {
                return ResourceManager.GetString("工位1图像处理完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Saving the Image 的本地化字符串。
        /// </summary>
        internal static string 工位1存图中 {
            get {
                return ResourceManager.GetString("工位1存图中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Failed to save the Image 的本地化字符串。
        /// </summary>
        internal static string 工位1存图失败 {
            get {
                return ResourceManager.GetString("工位1存图失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Save Image completed 的本地化字符串。
        /// </summary>
        internal static string 工位1存图完成 {
            get {
                return ResourceManager.GetString("工位1存图完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 taking the Image 的本地化字符串。
        /// </summary>
        internal static string 工位1拍照中 {
            get {
                return ResourceManager.GetString("工位1拍照中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Failed to  take the Image 的本地化字符串。
        /// </summary>
        internal static string 工位1拍照失败 {
            get {
                return ResourceManager.GetString("工位1拍照失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Image is taken 的本地化字符串。
        /// </summary>
        internal static string 工位1拍照完成 {
            get {
                return ResourceManager.GetString("工位1拍照完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Wait for the image signal 的本地化字符串。
        /// </summary>
        internal static string 工位1等待拍照信号 {
            get {
                return ResourceManager.GetString("工位1等待拍照信号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 1 Failed to read PLC signal 的本地化字符串。
        /// </summary>
        internal static string 工位1读取PLC信号失败 {
            get {
                return ResourceManager.GetString("工位1读取PLC信号失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Failed to write PLC signals 的本地化字符串。
        /// </summary>
        internal static string 工位2写入PLC信号失败 {
            get {
                return ResourceManager.GetString("工位2写入PLC信号失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Sending results 的本地化字符串。
        /// </summary>
        internal static string 工位2发送结果中 {
            get {
                return ResourceManager.GetString("工位2发送结果中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Sending results completed 的本地化字符串。
        /// </summary>
        internal static string 工位2发送结果完成 {
            get {
                return ResourceManager.GetString("工位2发送结果完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Image processing 的本地化字符串。
        /// </summary>
        internal static string 工位2图像处理中 {
            get {
                return ResourceManager.GetString("工位2图像处理中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2  Image processing completed 的本地化字符串。
        /// </summary>
        internal static string 工位2图像处理完成 {
            get {
                return ResourceManager.GetString("工位2图像处理完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Saving  the Image 的本地化字符串。
        /// </summary>
        internal static string 工位2存图中 {
            get {
                return ResourceManager.GetString("工位2存图中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Failed to  save the Image 的本地化字符串。
        /// </summary>
        internal static string 工位2存图失败 {
            get {
                return ResourceManager.GetString("工位2存图失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Save Image completed 的本地化字符串。
        /// </summary>
        internal static string 工位2存图完成 {
            get {
                return ResourceManager.GetString("工位2存图完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 taking the Image 的本地化字符串。
        /// </summary>
        internal static string 工位2拍照中 {
            get {
                return ResourceManager.GetString("工位2拍照中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Failed to  take the Image 的本地化字符串。
        /// </summary>
        internal static string 工位2拍照失败 {
            get {
                return ResourceManager.GetString("工位2拍照失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Image is taken 的本地化字符串。
        /// </summary>
        internal static string 工位2拍照完成 {
            get {
                return ResourceManager.GetString("工位2拍照完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Wait for the image signal 的本地化字符串。
        /// </summary>
        internal static string 工位2等待拍照信号 {
            get {
                return ResourceManager.GetString("工位2等待拍照信号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 2 Failed to read PLC signal 的本地化字符串。
        /// </summary>
        internal static string 工位2读取PLC信号失败 {
            get {
                return ResourceManager.GetString("工位2读取PLC信号失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera is connecting 的本地化字符串。
        /// </summary>
        internal static string 相机连接中 {
            get {
                return ResourceManager.GetString("相机连接中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera connection failed 的本地化字符串。
        /// </summary>
        internal static string 相机连接失败 {
            get {
                return ResourceManager.GetString("相机连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera connection completed 的本地化字符串。
        /// </summary>
        internal static string 相机连接完成 {
            get {
                return ResourceManager.GetString("相机连接完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running state 的本地化字符串。
        /// </summary>
        internal static string 运行状态 {
            get {
                return ResourceManager.GetString("运行状态", resourceCulture);
            }
        }
    }
}
