//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6524.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN_variable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN_variable() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_6524.Resources.EN_variable", typeof(EN_variable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The language setting is complete and takes effect after restarting the program 的本地化字符串。
        /// </summary>
        internal static string changeLanguageinfo {
            get {
                return ResourceManager.GetString("changeLanguageinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC is connecting 的本地化字符串。
        /// </summary>
        internal static string PLC连接中 {
            get {
                return ResourceManager.GetString("PLC连接中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC connection failed 的本地化字符串。
        /// </summary>
        internal static string PLC连接失败 {
            get {
                return ResourceManager.GetString("PLC连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC connection completed 的本地化字符串。
        /// </summary>
        internal static string PLC连接完成 {
            get {
                return ResourceManager.GetString("PLC连接完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 signal 的本地化字符串。
        /// </summary>
        internal static string 信号 {
            get {
                return ResourceManager.GetString("信号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The light  controller fails to be connected 的本地化字符串。
        /// </summary>
        internal static string 光源控制器连接失败 {
            get {
                return ResourceManager.GetString("光源控制器连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Failed to write PLC signals 的本地化字符串。
        /// </summary>
        internal static string 写入PLC信号失败 {
            get {
                return ResourceManager.GetString("写入PLC信号失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing 的本地化字符串。
        /// </summary>
        internal static string 初始化 {
            get {
                return ResourceManager.GetString("初始化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send results NG 的本地化字符串。
        /// </summary>
        internal static string 发送结果NG {
            get {
                return ResourceManager.GetString("发送结果NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send results OK 的本地化字符串。
        /// </summary>
        internal static string 发送结果OK {
            get {
                return ResourceManager.GetString("发送结果OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending results 的本地化字符串。
        /// </summary>
        internal static string 发送结果中 {
            get {
                return ResourceManager.GetString("发送结果中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending result completed 的本地化字符串。
        /// </summary>
        internal static string 发送结果完成 {
            get {
                return ResourceManager.GetString("发送结果完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image processing 的本地化字符串。
        /// </summary>
        internal static string 图像处理中 {
            get {
                return ResourceManager.GetString("图像处理中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image processing complete 的本地化字符串。
        /// </summary>
        internal static string 图像处理完成 {
            get {
                return ResourceManager.GetString("图像处理完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving image 的本地化字符串。
        /// </summary>
        internal static string 存图中 {
            get {
                return ResourceManager.GetString("存图中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to save image 的本地化字符串。
        /// </summary>
        internal static string 存图失败 {
            get {
                return ResourceManager.GetString("存图失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save complete 的本地化字符串。
        /// </summary>
        internal static string 存图完成 {
            get {
                return ResourceManager.GetString("存图完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Periodically delete the image 的本地化字符串。
        /// </summary>
        internal static string 定期删图完成 {
            get {
                return ResourceManager.GetString("定期删图完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 specified path can&apos;t be found  的本地化字符串。
        /// </summary>
        internal static string 定期删图找不到指定路径 {
            get {
                return ResourceManager.GetString("定期删图找不到指定路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete images regularly 的本地化字符串。
        /// </summary>
        internal static string 定期删除图片中 {
            get {
                return ResourceManager.GetString("定期删除图片中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 的本地化字符串。
        /// </summary>
        internal static string 工位 {
            get {
                return ResourceManager.GetString("工位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taking the photo 的本地化字符串。
        /// </summary>
        internal static string 拍照中 {
            get {
                return ResourceManager.GetString("拍照中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo slot 的本地化字符串。
        /// </summary>
        internal static string 拍照位 {
            get {
                return ResourceManager.GetString("拍照位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo failure 的本地化字符串。
        /// </summary>
        internal static string 拍照失败 {
            get {
                return ResourceManager.GetString("拍照失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo finish 的本地化字符串。
        /// </summary>
        internal static string 拍照完成 {
            get {
                return ResourceManager.GetString("拍照完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Robot camera connected failed 的本地化字符串。
        /// </summary>
        internal static string 机械手相机连接失败 {
            get {
                return ResourceManager.GetString("机械手相机连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Robot connecting 的本地化字符串。
        /// </summary>
        internal static string 机械手连接中 {
            get {
                return ResourceManager.GetString("机械手连接中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Robot connection failure 的本地化字符串。
        /// </summary>
        internal static string 机械手连接失败 {
            get {
                return ResourceManager.GetString("机械手连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera 的本地化字符串。
        /// </summary>
        internal static string 相机 {
            get {
                return ResourceManager.GetString("相机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera is connecting 的本地化字符串。
        /// </summary>
        internal static string 相机连接中 {
            get {
                return ResourceManager.GetString("相机连接中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait for photo bit 的本地化字符串。
        /// </summary>
        internal static string 等待拍照位 {
            get {
                return ResourceManager.GetString("等待拍照位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait for photo signal 的本地化字符串。
        /// </summary>
        internal static string 等待拍照信号 {
            get {
                return ResourceManager.GetString("等待拍照信号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read PLC signal 的本地化字符串。
        /// </summary>
        internal static string 读取PLC信号失败 {
            get {
                return ResourceManager.GetString("读取PLC信号失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running state 的本地化字符串。
        /// </summary>
        internal static string 运行状态 {
            get {
                return ResourceManager.GetString("运行状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is connecting 的本地化字符串。
        /// </summary>
        internal static string 连接中 {
            get {
                return ResourceManager.GetString("连接中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 connection fail 的本地化字符串。
        /// </summary>
        internal static string 连接失败 {
            get {
                return ResourceManager.GetString("连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 connection completed 的本地化字符串。
        /// </summary>
        internal static string 连接完成 {
            get {
                return ResourceManager.GetString("连接完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recipe table loading failed 的本地化字符串。
        /// </summary>
        internal static string 配方表载入失败 {
            get {
                return ResourceManager.GetString("配方表载入失败", resourceCulture);
            }
        }
    }
}
