//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6524.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ES_variable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ES_variable() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_6524.Resources.ES_variable", typeof(ES_variable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 La configuración de idioma es completa y tiene efecto después de reiniciar el programa 的本地化字符串。
        /// </summary>
        internal static string changeLanguageinfo {
            get {
                return ResourceManager.GetString("changeLanguageinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 El PLC se conecta 的本地化字符串。
        /// </summary>
        internal static string PLC连接中 {
            get {
                return ResourceManager.GetString("PLC连接中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fallo de conexión del PLC 的本地化字符串。
        /// </summary>
        internal static string PLC连接失败 {
            get {
                return ResourceManager.GetString("PLC连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Se ha completado la conexión del PLC 的本地化字符串。
        /// </summary>
        internal static string PLC连接完成 {
            get {
                return ResourceManager.GetString("PLC连接完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 La señal 的本地化字符串。
        /// </summary>
        internal static string 信号 {
            get {
                return ResourceManager.GetString("信号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controlador de fuente de luz no conectado 的本地化字符串。
        /// </summary>
        internal static string 光源控制器连接失败 {
            get {
                return ResourceManager.GetString("光源控制器连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 falló en escribir señales PLC 的本地化字符串。
        /// </summary>
        internal static string 写入PLC信号失败 {
            get {
                return ResourceManager.GetString("写入PLC信号失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iniciinicializar 的本地化字符串。
        /// </summary>
        internal static string 初始化 {
            get {
                return ResourceManager.GetString("初始化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enviar resultados NG 的本地化字符串。
        /// </summary>
        internal static string 发送结果NG {
            get {
                return ResourceManager.GetString("发送结果NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enviar resultados OK 的本地化字符串。
        /// </summary>
        internal static string 发送结果OK {
            get {
                return ResourceManager.GetString("发送结果OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enviar resultados 的本地化字符串。
        /// </summary>
        internal static string 发送结果中 {
            get {
                return ResourceManager.GetString("发送结果中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enviar resultados completos 的本地化字符串。
        /// </summary>
        internal static string 发送结果完成 {
            get {
                return ResourceManager.GetString("发送结果完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imagen en proceso 的本地化字符串。
        /// </summary>
        internal static string 图像处理中 {
            get {
                return ResourceManager.GetString("图像处理中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Procesamiento de imagen completo 的本地化字符串。
        /// </summary>
        internal static string 图像处理完成 {
            get {
                return ResourceManager.GetString("图像处理完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 guardar la imagen 的本地化字符串。
        /// </summary>
        internal static string 存图中 {
            get {
                return ResourceManager.GetString("存图中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no pudo guardar la imagen 的本地化字符串。
        /// </summary>
        internal static string 存图失败 {
            get {
                return ResourceManager.GetString("存图失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 guardar imagen completada 的本地化字符串。
        /// </summary>
        internal static string 存图完成 {
            get {
                return ResourceManager.GetString("存图完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eliminación periódica de gráficos completada 的本地化字符串。
        /// </summary>
        internal static string 定期删图完成 {
            get {
                return ResourceManager.GetString("定期删图完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No se puede encontrar la ruta especificada 的本地化字符串。
        /// </summary>
        internal static string 定期删图找不到指定路径 {
            get {
                return ResourceManager.GetString("定期删图找不到指定路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eliminar imágenes regularmente 的本地化字符串。
        /// </summary>
        internal static string 定期删除图片中 {
            get {
                return ResourceManager.GetString("定期删除图片中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estación 的本地化字符串。
        /// </summary>
        internal static string 工位 {
            get {
                return ResourceManager.GetString("工位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Foto en proceso 的本地化字符串。
        /// </summary>
        internal static string 拍照中 {
            get {
                return ResourceManager.GetString("拍照中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Espacio para fotos 的本地化字符串。
        /// </summary>
        internal static string 拍照位 {
            get {
                return ResourceManager.GetString("拍照位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no pudo tomar la imagen 的本地化字符串。
        /// </summary>
        internal static string 拍照失败 {
            get {
                return ResourceManager.GetString("拍照失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Foto terminada 的本地化字符串。
        /// </summary>
        internal static string 拍照完成 {
            get {
                return ResourceManager.GetString("拍照完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 La cámara del robot conectada falló 的本地化字符串。
        /// </summary>
        internal static string 机械手相机连接失败 {
            get {
                return ResourceManager.GetString("机械手相机连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conexión de robots 的本地化字符串。
        /// </summary>
        internal static string 机械手连接中 {
            get {
                return ResourceManager.GetString("机械手连接中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error de conexión del manipulador 的本地化字符串。
        /// </summary>
        internal static string 机械手连接失败 {
            get {
                return ResourceManager.GetString("机械手连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cámara  的本地化字符串。
        /// </summary>
        internal static string 相机 {
            get {
                return ResourceManager.GetString("相机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 La cámara se conecta 的本地化字符串。
        /// </summary>
        internal static string 相机连接中 {
            get {
                return ResourceManager.GetString("相机连接中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fallo en la conexión de la cámara 的本地化字符串。
        /// </summary>
        internal static string 相机连接失败 {
            get {
                return ResourceManager.GetString("相机连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conexión a la cámara fotográfica completada 的本地化字符串。
        /// </summary>
        internal static string 相机连接完成 {
            get {
                return ResourceManager.GetString("相机连接完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Esperando la sesión de fotos 的本地化字符串。
        /// </summary>
        internal static string 等待拍照位 {
            get {
                return ResourceManager.GetString("等待拍照位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 espere la señal de imagen 的本地化字符串。
        /// </summary>
        internal static string 等待拍照信号 {
            get {
                return ResourceManager.GetString("等待拍照信号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no pudo leer la señal del PLC 的本地化字符串。
        /// </summary>
        internal static string 读取PLC信号失败 {
            get {
                return ResourceManager.GetString("读取PLC信号失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estado de ejecución 的本地化字符串。
        /// </summary>
        internal static string 运行状态 {
            get {
                return ResourceManager.GetString("运行状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conectado en progreso 的本地化字符串。
        /// </summary>
        internal static string 连接中 {
            get {
                return ResourceManager.GetString("连接中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no se conecta 的本地化字符串。
        /// </summary>
        internal static string 连接失败 {
            get {
                return ResourceManager.GetString("连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 La conexión completa 的本地化字符串。
        /// </summary>
        internal static string 连接完成 {
            get {
                return ResourceManager.GetString("连接完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error al cargar la tabla de recetas 的本地化字符串。
        /// </summary>
        internal static string 配方表载入失败 {
            get {
                return ResourceManager.GetString("配方表载入失败", resourceCulture);
            }
        }
    }
}
